export const GENERATE_LOCATION = "GENERATE_LOCATION";
export const POPULATE_LOCATION = "POPULATE_LOCATION";
export const GENERATE_BUTTON = "GENERATE_BUTTON";
export const DISABLE_BUTTON = "DISABLE_BUTTON";